###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
Content-Type: application/json

{
    "contents": [{ 
        "parts":[{"text": "Please explain how AI works in a few words."}]
    }]
}

###
GET http://localhost:3000/get
Authorization: Basic admin:supersecret

###
GET http://localhost:3000/podetails
Authorization: Basic admin:supersecret

###
POST http://localhost:3000/post
Authorization: Basic testUser:Megavnn123@@

{
    "contents": [{ 
        "parts":[{"text": "Explain how AI works"}]
    }]
}

###
GET http://localhost:3000/podetails
Authorization: Basic testUser:Megavnn123@@

###
GET https://my402028.s4hana.cloud.sap/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/PurchaseOrder?$top=5&$count=true
Authorization: Basic 
Accept: application/json
X-CSRF-Token: fetch

###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata4/sap/api_purchaseorder_2/srvd_a2x/sap/purchaseorder/0001/PurchaseOrderItem?$top=5&$count=false
APIKey: "CuZbkJRtlUMBAtEKZIkrg0DC1EGPjDgh"
Accept: application/json
X-CSRF-Token: fetch

